let data  = [{
	"algorithm":"Bubble sort",
    "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "cppCode":"",
    "cCode":"",
    "pythonCode":"",
    "javascriptCode":""
},
{
	"algorithm":"Insertion sort",
    "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "cppCode":"",
    "cCode":"",
    "pythonCode":"",
    "javascriptCode":''
},
{
	"algorithm":"Selection sort",
    "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "cppCode":"",
    "cCode":"",
    "pythonCode":"",
    "javascriptCode":""
}, 
{
	"algorithm":"Counting sort",
    "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "cppCode":'<p><span class="red">#include</span> <span class="blue">&lt;iostream&gt;</span></p><p><span class="red">using namespace</span> std;</p><p>int max(int arr[], int n){</p><p class="tab">int high;</p><p class="tab"><span class="red">for</span> (int i <span class="red">=</span> 0 ; i <span class="red"><</span> n ; i<span class="red">++</span>){</p><p class="tabb"><span class="red">if</span> (arr[i] <span class="red">></span> high)</p><p class="tabbb">high <span class="red">=</span> arr[i];</p><p class="tabb">}</p><p class="tab"><span class="red">return</span> high;</p><p>}</p><p>void countingSort(int <span class="red">*</span>arr, int n){</p><p class="tab">int maxNub <span class="red">=</span> max(arr, n);</p><p class="tab">int count[maxNub];</p><p class="tab"><span class="red">for</span>(int i; i <span class="red"><</span> maxNub;i<span class="red">++</span>){count[i] <span class="red">=</span> 0;}</p><p class="tab">int sort[n];</p><p class="tab"><span class="red">for</span>(int i; i <span class="red"><</span> n;i<span class="red">++</span>){sort[i] <span class="red">=</span> 0;}</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i < n; i<span class="red">++</span>){</p><p class="tabb">count[(arr[i])<span class-"red">=</span>1] <span class="red">+=</span> 1;</p><p class="tab">}</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i < maxNub<span class="red">-</span>1; i<span class="red">++</span>){</p><p class="tabb">count[i<span class="red">+</span>1] <span class="red">+=</span> count[i];</p><p class="tab">}</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i <span class="red"><</span> n; i<span class="red">++</span>){</p><p class="tabb">sort[count[arr[i]<span class="red">-</span>1]<span class="red">-</span>1] <span class="red">=</span> arr[i];</p><p class="tabb">count[arr[i]<span class="red">-</span>1] <span class="red">-=</span> 1;</p><p class="tab">}</p><p class="tab">for(int i <span class="red">=</span> 0; i <span class="red"><</span> n; i<span class="red">++</span>){</p><p class="tabb">arr[i] <span class="red">=</span> sort[i];</p><p class="tab">}</p><p>}<p><p>int main(){</p><p class="tab">cout <span class="red"><<</span> "";</p><p class="tab">int arr[5] <span class="red">=</span> { 12, 34, 54, 2, 3};</p><p class="tab">countingSort(arr, 5);</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i < 5; i<span class="red">++</span>){</p><p class="tabb">cout <span class="red"><<</span> arr[i] <span class="red"><<</span> <span class="yellow">" "</span>;</p><p class="tab">}</p><p class="tab"><span class="red">return</span> 0;</p><p>}</p>',
    "cCode":'					<p><span class="red">#include</span> <span class="blue">&lt;iostream&gt;</span></p><p><span class="red">using namespace</span> std;</p><p>int max(int arr[], int n){</p><p class="tab">int high;</p><p class="tab"><span class="red">for</span> (int i <span class="red">=</span> 0 ; i <span class="red"><</span> n ; i<span class="red">++</span>){</p><p class="tabb"><span class="red">if</span> (arr[i] <span class="red">></span> high)</p><p class="tabbb">high <span class="red">=</span> arr[i];</p><p class="tabb">}</p><p class="tab"><span class="red">return</span> high;</p><p>}</p><p>void countingSort(int <span class="red">*</span>arr, int n){</p><p class="tab">int maxNub <span class="red">=</span> max(arr, n);</p><p class="tab">int count[maxNub];</p><p class="tab"><span class="red">for</span>(int i; i <span class="red"><</span> maxNub;i<span class="red">++</span>){count[i] <span class="red">=</span> 0;}</p><p class="tab">int sort[n];</p><p class="tab"><span class="red">for</span>(int i; i <span class="red"><</span> n;i<span class="red">++</span>){sort[i] <span class="red">=</span> 0;}</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i < n; i<span class="red">++</span>){</p><p class="tabb">count[(arr[i])<span class-"red">=</span>1] <span class="red">+=</span> 1;</p><p class="tab">}</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i < maxNub<span class="red">-</span>1; i<span class="red">++</span>){</p><p class="tabb">count[i<span class="red">+</span>1] <span class="red">+=</span> count[i];</p><p class="tab">}</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i <span class="red"><</span> n; i<span class="red">++</span>){</p><p class="tabb">sort[count[arr[i]<span class="red">-</span>1]<span class="red">-</span>1] <span class="red">=</span> arr[i];</p><p class="tabb">count[arr[i]<span class="red">-</span>1] <span class="red">-=</span> 1;</p><p class="tab">}</p><p class="tab">for(int i <span class="red">=</span> 0; i <span class="red"><</span> n; i<span class="red">++</span>){</p><p class="tabb">arr[i] <span class="red">=</span> sort[i];</p><p class="tab">}</p><p>}<p><p>int main(){</p><p class="tab"><span class="red">printf</span>(<span class="yellow">""</span>);</p><p class="tab">int arr[5] <span class="red">=</span> { 12, 34, 54, 2, 3};</p><p class="tab">countingSort(arr, 5);</p><p class="tab"><span class="red">for</span>(int i <span class="red">=</span> 0; i < 5; i<span class="red">++</span>){</p><p class="tabb"><span class="red">printf</span>(<span class="yellow">"</span><span class="blue">%d</span> <span class="yellow">"</span>, arr[i]);</p><p class="tab">}</p><p class="tab"><span class="red">return</span> 0;</p><p>}</p>',
    "pythonCode":'<p><span class="orange">def</span> <span class="blue">countingSort</span>(arr):</p><p class="tab">sort = [0]*<span class="blue">len</span>(arr)</p><p class="tab">count = [0]*<span class="blue">max</span>(arr)</p><p class="tab"><span class="orange">for</span> i in <span class="blue">range</span>(<span class="blue">len</span>(arr)):</p><p class="tabb">count[(arr[i])-1] += 1</p><p class="tab"><span class="orange">for</span> i in <span class="blue">range</span>(<span class="blue">len</span>(count)-1):</p><p class="tabb">count[i+1] += count[i]</p><p class="tab"><span class="orange">for</span> i in <span class="blue">range</span>(<span class="blue">len</span>(arr)):</p><p class="tabb">sort[count[arr[i]-1]-1] = arr[i]</p><p class="tabb">count[arr[i]-1] -= 1</p><p class="tab"><span class="orange">return</span> sort</p><p>listi = [ 12, 34, 54, 2, 3]</p><p><span class="blue">print</span>(countingSort(listi))</p>',
    "javascriptCode":'<p><span class="blue">function</span> <span class="yellow">countingSort</span>(<span class="orange"> arr</span>){</p><p class="tab">(sort <span class="red">=</span> []).length <span class="red">=</span> arr.length;</p><p class="tab">sort.<span class="blue">fill</span>(<span class="blue">0</span>);</p><p class="tab">(count <span class="red">=</span> []).length <span class="red">=</span> <span class="blue">Math</span>.<span class="blue">max</span>(<span class="red">...</span>arr);</p><p class="tab">count.<span class="blue">fill</span>(<span class="blue">0</span>);</p><p class="tab"><span class="red">for</span>(<span class="blue">let</span> i <span class="red">=</span> 0; i < arr.length; i<span class="red">++</span>){</p><p class="tabb">count[(arr[i])-1] <span class="red">+=</span> 1;</p><p class="tab">}</p><p class="tab"><span class="red">for</span>(let i <span class="red">=</span> 0; i < count.length<span class="red">-</span>1; i<span class="red">++</span>){</p><p class="tabb">count[i<span class="red">+</span>1] <span class="red">+=</span> count[i];</p><p class="tab">}</p><p class="tab"><span class="red">for</span>(<span class="blue">let</span> i <span class="red">=</span> 0; i < arr.length; i<span class="red">++</span>){</p><p class="tabb">sort[count[arr[i]<span class="red">-</span>1]<span class="red">-</span>1] <span class="red">=</span> arr[i];</p><p class="tabb">count[arr[i]<span class="red">-</span>1] <span class="red">-=</span> 1;</p><p class="tab">}</p><p class="tab"><span class="red">return</span> sort;</p><p>}</p><p>let arr = [12, 34, 54, 2, 3];</p><p>arr = countingSort(arr);</p><p>console.log(arr);</p>'
},
{
	"algorithm":"Shell sort",
    "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "cppCode":"",
    "cCode":"",
    "pythonCode":"",
    "javascriptCode":""
},
{
	"algorithm":"Quick sort",
	"description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
	"codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
	"cppCode":"",
	"cCode":"",
	"pythonCode":"",
	"javascriptCode":""
},
{
	"algorithm":"Heap sort",
    "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "cppCode":"",
    "cCode":"",
    "pythonCode":"",
    "javascriptCode":""
},
{
	"algorithm":"Merge sort",
    "description":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "codeDescription":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "cppCode":"",
    "cCode":"",
    "pythonCode":"",
    "javascriptCode":""
}
];